### ISSUE TITLE
oAuth Authentication

### ISSUE THREAD

**Issue by sprankhub** [santerref/mag-products-integration#1]
First of all, thanks for the plugin!

I am not sure how you currently retrieve the products without authentication. In any case, I think this is a must-have feature. Any time frame for the implementation of oAuth?

**Comment by santerref** [comment]
Hi @sprankhub !

Thanks for your feedback.

I agree that this is a must-have feature and it should be available soon (mid-november or end of november).

Currently, you must create a user with the Guest role. This is a public role that let you retrieve your products without authentification: http://magentowp.santerref.com/plugin/documentation-1.0.pdf

santerref

**Comment by sprankhub** [comment]
Any update on this? :) Thanks!

**Comment by sprankhub** [comment]
I guess this is a no? :-) Would it be possible to sponsor that feature somehow (not sure if my client would do it, but that could be an option)?

**Comment by santerref** [comment]
Hi @sprankhub,

There is a work in progress in branch release/1.3.0 https://github.com/santerref/mag-products-integration/tree/release/1.3.0

The new settings have been added and the login button is working.

I have to finish the OAuth process and use the user token to make the requests.

I will be able to finish this before holidays :) !

santerref.

**Comment by danielchicote** [comment]
Hello, oauth is not available for php 7.2. Any alternative to downgrade my php version?

**Comment by santerref** [comment]
Hi @danielchicote,

It seems like https://pecl.php.net/package/oauth OAuth 2.0.3 and 2.0.4 are working with PHP 7.2 but I have not tested it yet.

You might have to install it manually with PECL.

santerref

**Comment by sprankhub** [comment]
Any update @santerref? Thanks! :-)

**Comment by santerref** [comment]
@sprankhub  !

Since Magento 1 will reach it's EOF (end of life) next 20 june https://magento.com/blog/magento-news/supporting-magento-1-through-june-2020

I will no longer add features for the Magento 1 version of Mag Products Integration.

I will not finish the oAuth feature since the version used by Magento is outdated and it takes me too much effort on getting this working.

Will release soon a new version that support Magento 2 but unfortunately you will have to use the Guest user to retrieve your products.

The Magento 2 version will use REST API with authentication.

I hope you still enjoy the plugin and you will continue to use it.

santerref

**Comment by sprankhub** [comment]
Pity. Magento 1 will be around for quite some time and there are [multiple approaches](https://openmage.github.io/magento-lts/alternatives.html) to further support it. Anyway, I have to accept your decision ¯\\_(ツ)_/¯

**Comment by santerref** [comment]
@sprankhub I am open to add new features to the Magento 1 version however I don't understand why OAuth it's a must have. When you sell your products, you want people to see them? Same thing when you show them on your WP site, right? So what is the problem with using a guest role that has only the permission to retrieve products data (which is already public)?

You can add some security in your .htaccess or web server to allow requests to /api/rest/ only from whitelisted IPs :) !

**Comment by sprankhub** [comment]
To be honest, I did not know that you can select the product attributes, which are returned. This at least improves the situation. However, I guess that still too much data is returned (not salable products for example)...

**Comment by santerref** [comment]
@sprankhub There are filters to choose which products should be returned. This is all done in the WP plugin. I do not know every possible use case since every Magento store is unique but it should work most of the times. 

If you have products you don't want in you WP, just let me know what is the product and its attributes and I should be able to add some filters to remove this or these products. Just open another issue and I will help you with that.

If you don't want people to find your hidden products with the API, just restrict the access by IP :) ! Something like that : 

```
<Directory /path/to/the/folder>
            Options +Indexes
            IndexOptions +FancyIndexing
            Order deny,allow
            Deny from all
            Allow from X.X.X.X
</Directory>
```
